### ISSUE TITLE
Please add osint cellular 

### ISSUE THREAD

**Issue by MasJuna** [Jieyab89/OSINT-Cheat-sheet-#4]
Add cellular osint tools investigation

**Comment by Jieyab89** [comment]
Soon, ASAP

**Comment by Jieyab89** [comment]
Solved, check my commit today https://github.com/Jieyab89/OSINT-Cheat-sheet-/commit/b70a00e5a99ef0e291f2822a068b256938f1d0c4

**Comment by MasJuna** [comment]
Thx Jieyab!
